import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../../../..');
const read = (relativePath: string): string => readFileSync(join(projectRoot, relativePath), 'utf8');

test('keeps the Excel presentation route dev-only and exercises the real viewer boundary', () => {
  const routes = read('src/app/app.routes.ts');
  const app = read('src/app/app.component.ts');
  const demo = read('src/app/features/documents/excel-document-demo.component.ts');
  const viewer = read('src/app/features/documents/excel-document-viewer.component.ts');
  const previewModal = read('src/app/features/documents/document-preview-modal.component.ts');
  const metadata = read('src/app/features/documents/excel-univer-metadata.ts');
  const angularConfig = JSON.parse(read('angular.json')) as {
    projects: Record<string, { architect?: { build?: { options?: { styles?: string[] } } } }>;
  };
  const globalStyles = angularConfig.projects['lims-cloud-pro']?.architect?.build?.options?.styles ?? [];
  const univerStyles = [
    'node_modules/@univerjs/preset-sheets-core/lib/index.css',
    'node_modules/@univerjs/preset-sheets-filter/lib/index.css',
    'node_modules/@univerjs/preset-sheets-find-replace/lib/index.css',
    'node_modules/@univerjs/preset-sheets-hyper-link/lib/index.css',
    'node_modules/@univerjs/preset-sheets-note/lib/index.css',
    'node_modules/@univerjs/preset-sheets-sort/lib/index.css',
  ];

  assert.match(routes, /path: '__excel-demo'/);
  assert.match(routes, /environment\.production \? \[\] :/);
  assert.match(app, /url\.startsWith\('\/__excel-demo'\)/);
  assert.match(demo, /<app-excel-document-viewer/);
  assert.match(demo, /LIMS_Excel_Preview_Demo\.xlsx/);
  assert.match(demo, /Ctrl\+A chọn vùng/);
  assert.match(demo, /Ctrl\+Shift\+L mở Filter/);
  assert.match(demo, /Nhấn Ctrl\+F để mở công cụ tìm kiếm/);
  assert.match(demo, /new Date\(2026, 7, 22, 15, 30, 45, 250\)/);
  assert.match(demo, /!autofilter/);
  assert.match(demo, /yyyy-mm-dd hh:mm:ss\.000/);
  assert.doesNotMatch(demo, /Date\.UTC/);
  assert.match(viewer, /createUniver\(/);
  assert.match(viewer, /aria-readonly="true"/);
  assert.match(viewer, /data-excel-readonly="true"/);
  assert.match(viewer, /previewWorkbook\.setEditable\(false\)/);
  assert.match(viewer, /previewWorkbook\.getWorkbookPermission\(\)\.setReadOnly\(\)/);
  assert.match(viewer, /worksheet\.getWorksheetPermission\(\)\.setReadOnly\(\)/);
  assert.match(viewer, /applyPreservedMetadata\(/);
  assert.match(viewer, /applyExcelAutoFilterSafely\(/);
  assert.match(viewer, /try \{\s*await this\.applyPreservedMetadata\(/);
  assert.match(viewer, /Keep the workbook visible and degrade only the incompatible metadata/);
  assert.match(viewer, /worksheet\.setFreeze\(/);
  assert.match(viewer, /\.createFilter\(\)/);
  assert.match(viewer, /\.setHyperLink\(/);
  assert.match(viewer, /\.createOrUpdateNote\(/);
  assert.match(viewer, /unsupportedFeatures\(\)/);
  assert.match(metadata, /conditionalFormatting/);
  assert.match(viewer, /toolbar:\s*false/);
  assert.match(viewer, /contextMenu:\s*false/);
  assert.match(viewer, /formulaBar:\s*false/);
  assert.doesNotMatch(viewer, /formulaBar:\s*true/);
  assert.match(viewer, /excel-view-only/);
  assert.match(viewer, /key === 'h'/);
  assert.match(viewer, /key === 'a'/);
  assert.match(viewer, /key === 'l'/);
  assert.match(viewer, /excel-view-tools-bar/);
  assert.match(viewer, /Tìm kiếm trong workbook \(Ctrl\+F\)/);
  assert.match(viewer, /Chọn nhanh vùng dữ liệu \(Ctrl\+A\)/);
  assert.match(viewer, /<span>Filter<\/span>/);
  assert.match(viewer, /Ctrl\+Shift\+L/);
  assert.match(viewer, /Đi tới ô hoặc vùng \(Ctrl\+G\)/);
  assert.match(viewer, /Vừa chiều rộng vùng dữ liệu/);
  assert.match(viewer, /Đặt lại cách xem/);
  assert.match(viewer, /Thêm công cụ xem/);
  assert.match(viewer, /openFindDialog\(\)/);
  assert.match(viewer, /selectPreviewDataRange\(\)/);
  assert.match(viewer, /applyPreviewFilter\(\)/);
  assert.match(viewer, /ui\.operation\.open-find-dialog/);
  assert.match(viewer, /sheet\.operation\.open-filter-panel/);
  assert.match(viewer, /getApplicableExcelAutoFilterRange/);
  assert.match(viewer, /getPreviewFilterCandidateRange/);
  assert.doesNotMatch(viewer, /\[disabled\]="!autoFilterTargets\(\)\.length"/);
  assert.doesNotMatch(viewer, /excel-readonly-bar/);
  assert.doesNotMatch(viewer, /Chỉ xem nội dung · không thể nhập hoặc thay đổi bảng tính gốc/);
  assert.doesNotMatch(previewModal, /Chỉ đọc/);
  assert.match(viewer, /centerPreviewSelection\(\)/);
  assert.match(viewer, /togglePreviewWrapText\(\)/);
  assert.match(viewer, /autofitPreview\(\)/);
  assert.match(viewer, /sortPreview\(true\)/);
  assert.match(viewer, /sortPreview\(false\)/);
  assert.match(viewer, /UniverSheetsSortPreset/);
  assert.match(viewer, /installReadonlyInteractionGuard\(\)/);
  assert.match(viewer, /addEventListener\('dblclick'/);
  assert.match(viewer, /addEventListener\('keydown'/);
  assert.match(viewer, /addEventListener\('beforeinput'/);
  assert.match(viewer, /addEventListener\('paste'/);
  assert.match(viewer, /setAttribute\('contenteditable', 'false'\)/);
  assert.match(viewer, /MutationObserver\(enforceReadonlyEditorSurface\)/);
  assert.match(viewer, /sheetBar:\s*true/);
  assert.match(viewer, /zoomSlider:\s*true/);
  assert.match(viewer, /addSheetButtonConfig:\s*\{ show: false \}/);
  assert.doesNotMatch(viewer, /toolbar:\s*true/);
  assert.doesNotMatch(viewer, /contextMenu:\s*true/);
  assert.match(viewer, /runPreviewTool\(/);
  assert.match(viewer, /openPreviewContextMenu\(\$event\)/);
  assert.match(viewer, /buildExcelPreviewContextMenu\(/);
  assert.match(viewer, /contextMenu:\s*false/);
  assert.match(viewer, /role="menu"/);
  assert.match(viewer, /role="menuitem"/);
  assert.match(viewer, /submenu-format/);
  assert.match(viewer, /toggleSubmenu\(/);
  assert.match(viewer, /ArrowRight/);
  assert.match(viewer, /ArrowLeft/);
  assert.match(viewer, /openScopedFind\(/);
  assert.match(viewer, /excel-scoped-find/);
  assert.match(viewer, /previewFilterSummaries/);
  assert.match(viewer, /getFilterViewDetails\(/);
  assert.match(viewer, /viewStateChips/);
  assert.match(viewer, /copyPreviewSelection\(/);
  assert.match(viewer, /parseExcelGoToTarget\(/);
  assert.match(viewer, /fitPreviewWidth\(\)/);
  assert.match(viewer, /fitPreviewSelection\(\)/);
  assert.match(viewer, /resetPreviewZoom\(\)/);
  assert.match(viewer, /showSelectionInfo\(\)/);
  assert.match(viewer, /openDimensionEditor\(/);
  assert.match(viewer, /openSheetList\(\)/);
  assert.match(viewer, /goToHistory/);
  assert.match(viewer, /startLongPress/);
  assert.match(viewer, /pointerType !== 'touch'/);
  assert.match(viewer, /setColumnWidths\(/);
  assert.match(viewer, /setRowHeights\(/);
  assert.match(viewer, /applyBlankFilter\(/);
  assert.match(viewer, /ExcelPreviewViewChangeKind/);
  assert.match(viewer, /clearViewChange\(/);
  assert.match(viewer, /resetPreviewTargetView\(/);
  assert.match(viewer, /viewChangeUndo/);
  assert.match(viewer, /removeUniverEvents/);
  assert.match(viewer, /ActiveSheetChanged/);
  assert.match(viewer, /SheetRangeFiltered/);
  assert.match(viewer, /isSafeExcelHyperlink/);
  assert.match(viewer, /pointerType !== 'touch'/);
  assert.match(viewer, /removeFilterCriteria\(\)/);
  assert.match(viewer, /Thống kê vùng đang chọn/);
  assert.match(viewer, /50_000/);
  assert.match(viewer, /resetPreviewView\(\)/);
  assert.match(viewer, /resetWorkbookFromSource\(\)/);
  assert.match(viewer, /sourceSnapshot/);
  assert.match(viewer, /structuredClone\(sourceSnapshot\)/);
  assert.match(viewer, /disposeUnit\(activeUnitId\)/);
  assert.match(viewer, /lockPreviewWorkbook\(/);
  assert.match(viewer, /hideSelectedColumns\(\)/);
  assert.match(viewer, /hideSelectedRows\(\)/);
  assert.doesNotMatch(viewer, /setAttribute\('contenteditable', 'true'\)/);
  assert.doesNotMatch(viewer, /UniverSheetsConditionalFormattingPreset/);
  assert.doesNotMatch(viewer, /UniverSheetsDataValidationPreset/);
  assert.doesNotMatch(viewer, /UniverSheetsDrawingPreset/);
  assert.doesNotMatch(viewer, /UniverSheetsTablePreset/);
  assert.match(viewer, /excel-univer-host > div:first-child/);
  for (const stylePath of univerStyles) {
    assert.ok(globalStyles.includes(stylePath), `Univer CSS must be loaded globally: ${stylePath}`);
    assert.doesNotMatch(viewer, new RegExp(`import ['"]${stylePath.replaceAll('/', '\\/')}['"];`));
  }
});
